### ISSUE TITLE
Project notworking

### ISSUE THREAD

**Issue by minhyentcu** [d3fault1/MT5DataFeed#1]
**Could not load file or assembly 'MetaQuotes.MT5CommonAPI64' or one of its dependencies. An attempt was made to load a program with an incorrect format.**

I tried running your code but got the same error as above. Can you help me.
Hope you reply soon. Thank you very much!

**Comment by d3fault1** [comment]
You should change the platform configuration to x64 instead of x86_64 before compiling the project.

**Comment by minhyentcu** [comment]
> You should change the platform configuration to x64 instead of x86_64 before compiling the project.

Visual studio default is **x64** . I tried converting to **x64** instead (**Any CPU**) but still not working. Can you help me. Do you use telegram or FB, can you contact me.
Thank you very much.
Hope to hear from you soon!

**Comment by minhyentcu** [comment]
Visual studio default is *x64* . I tried converting to* x64* instead (*Any
CPU*) but still not working. Can you help me. Do you use telegram or FB,
can you contact me.
[image: image.png]
[image: image.png]
Thank you very much.
Hope to hear from you soon!

Vào Th 4, 8 thg 3, 2023 vào lúc 05:14 d3fault1 ***@***.***>
đã viết:
